#!/usr/bin/env python3
# coding: utf8

"""
Font Data Generator
Scans for .otf font files in imports/fonts/ and generates a fonts_data.py file
with base64 encoded font data for PyInstaller compatibility.
"""

import os
import base64
from pathlib import Path
import re


def sanitize_key_name(filename: str) -> str:
    """Convert filename to a valid Python dictionary key"""
    # Remove extension and convert to lowercase
    name = filename.lower().replace('.otf', '')
    # Replace non-alphanumeric characters with underscores
    name = re.sub(r'[^a-z0-9]+', '_', name)
    # Remove leading/trailing underscores
    name = name.strip('_')
    return name


def encode_font_to_base64(font_path: str) -> str:
    """Read font file and encode it as base64 string"""
    with open(font_path, 'rb') as font_file:
        font_data = font_file.read()
        base64_data = base64.b64encode(font_data).decode('utf-8')
        return base64_data


def generate_fonts_data_file(fonts_dir: str, output_file: str):
    """Generate fonts_data.py file with all OTF fonts encoded as base64"""
    
    fonts_path = Path(fonts_dir)
    if not fonts_path.exists():
        print(f"Fonts directory not found: {fonts_dir}")
        return
    
    # Find all .otf files
    otf_files = list(fonts_path.glob('*.otf'))
    if not otf_files:
        print(f"No .otf files found in {fonts_dir}")
        return
    
    print(f"Found {len(otf_files)} font file(s):")
    for font_file in otf_files:
        print(f"  - {font_file.name}")
    
    # Generate the Python file content
    content_lines = [
        '#! python3.11',
        '# coding: utf8',
        '',
        '""" Base64 encoded font data """',
        '# This file is auto-generated by generate_fonts_data.py',
        '# Do not edit manually - changes will be overwritten',
        '',
        'font_dict = {'
    ]
    
    # Process each font file
    for font_file in otf_files:
        print(f"Processing {font_file.name}...")
        
        # Create dictionary key from filename
        key_name = sanitize_key_name(font_file.name)
        
        # Encode font to base64
        try:
            base64_data = encode_font_to_base64(str(font_file))
            
            # Add to content
            content_lines.extend([
                f'    "{key_name}": (',
                f'        "{base64_data}"',
                '    ),'
            ])
            
            print(f"  ✓ Encoded as key: '{key_name}'")
            
        except Exception as e:
            print(f"  ✗ Error processing {font_file.name}: {e}")
            continue
    
    # Close the dictionary
    content_lines.append('}')
    
    # Write the file
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(content_lines))
    
    print(f"\n✓ Generated {output_file}")
    print(f"Font keys available: {[sanitize_key_name(f.name) for f in otf_files]}")


def main():
    """Main function"""
    script_dir = Path(__file__).parent
    fonts_dir = script_dir  # Now we're in the fonts directory
    output_file = script_dir / "fonts_data.py"
    
    print("Font Data Generator")
    print("=" * 50)
    print(f"Scanning directory: {fonts_dir}")
    print(f"Output file: {output_file}")
    print()
    
    generate_fonts_data_file(str(fonts_dir), str(output_file))


if __name__ == "__main__":
    main()