#!/usr/bin/env python3
"""
Font Base64 Converter

Scans the sibling fonts/ directory for supported font files and generates
fonts_byte64.py containing a dictionary mapping {name: base64_str}.

Usage:
    python3 fonts.py

Supported extensions: .ttf, .otf
Notes:
- Embedding fonts as base64 ensures the app has a consistent UI font even when
  the host system lacks the font installed.
- At runtime, use QFontDatabase.addApplicationFontFromData(bytes) to register
  fonts, then set QApplication's default font.
"""
import base64
import pathlib
import sys
from typing import Dict

ROOT = pathlib.Path(__file__).resolve().parent
SRC_DIR = ROOT  # scan current fonts/ folder
OUT_FILE = ROOT / 'fonts_byte64.py'
SUPPORTED = {'.ttf', '.otf'}

HEADER = """# Auto-generated by fonts/fonts.py; do not edit.
FONTS = {
"""
FOOTER = """
}

# Helper: decode base64 to bytes

def get_bytes(name: str):
    import base64
    s = FONTS.get(name)
    return base64.b64decode(s) if s else None
"""


def collect_fonts() -> Dict[str, str]:
    fonts: Dict[str, str] = {}
    for p in SRC_DIR.iterdir():
        if p.is_dir():
            for q in p.rglob('*'):
                if q.is_file() and q.suffix.lower() in SUPPORTED:
                    name = q.stem
                    try:
                        b64 = base64.b64encode(q.read_bytes()).decode('ascii')
                        fonts[name] = b64
                    except Exception as e:
                        print(f"[warn] failed to encode {q}: {e}")
            continue
        if p.is_file() and p.suffix.lower() in SUPPORTED:
            name = p.stem
            try:
                b64 = base64.b64encode(p.read_bytes()).decode('ascii')
                fonts[name] = b64
            except Exception as e:
                print(f"[warn] failed to encode {p}: {e}")
    return fonts


def write_output(fonts: Dict[str, str]) -> None:
    with OUT_FILE.open('w', encoding='utf-8') as f:
        f.write(HEADER)
        for name, b64 in sorted(fonts.items()):
            f.write(f"    '{name}': '{b64}',\n")
        f.write(FOOTER)
    print(f"[ok] wrote {OUT_FILE} with {len(fonts)} fonts")


if __name__ == '__main__':
    fonts = collect_fonts()
    write_output(fonts)
    sys.exit(0)
